Repository flexion/ef-cms, pull requests merged in 2019-06, with the labels that each got.

#1924 1066- changing the dynamsoft url
  web-client/terraform/dynamsoft/dynamsoft.tf
  web-client/terraform/main/main.tf
Labels: don't merge

#1919 1066 generate pdf
  Dockerfile
  efcms-service/src/applicationContext.js
  shared/src/business/useCases/generatePDFFromPNGDataInteractor.js
  shared/src/business/useCases/generatePDFFromPNGDataInteractor.test.js
  shared/src/business/useCases/getScannerInterfaceInteractor.js
  shared/src/business/useCases/getScannerInterfaceInteractor.test.js
  shared/test-assets/dynamsoft.webtwain.config.js
  shared/test-assets/dynamsoft.webtwain.initiate.js
  shared/test-assets/sample.png
  web-client/src/applicationContext.js
  web-client/src/index.pug
  web-client/src/presenter/actions/completeScanAction.js
  web-client/src/presenter/actions/completeScanAction.test.js
  web-client/src/presenter/actions/getCachedScannerSourceAction.js
  web-client/src/presenter/actions/getCachedScannerSourceAction.test.js
  web-client/src/presenter/actions/getScannerSourcesAction.js
  web-client/src/presenter/actions/getScannerSourcesAction.test.js
  web-client/src/presenter/actions/scannerShutdownAction.js
  web-client/src/presenter/actions/scannerShutdownAction.test.js
  web-client/src/presenter/actions/scannerStartupAction.js
  web-client/src/presenter/actions/scannerStartupAction.test.js
  web-client/src/presenter/actions/setScannerSourceAction.js
  web-client/src/presenter/actions/setScannerSourceAction.test.js
  web-client/src/presenter/actions/startScanAction.js
  web-client/src/presenter/actions/startScanAction.test.js
  web-client/src/presenter/computeds/scanHelper.js
  web-client/src/presenter/computeds/scanHelper.test.js
  web-client/src/presenter/presenter.js
  web-client/src/presenter/sequences/completeScanSequence.js
  web-client/src/presenter/sequences/scannerShutdownSequence.js
  web-client/src/presenter/sequences/scannerStartupSequence.js
  web-client/src/presenter/sequences/setScannerSourceSequence.js
  web-client/src/presenter/sequences/setScannerSourceSequence.test.js
  web-client/src/presenter/sequences/startScanSequence.js
  web-client/src/presenter/sequences/startScanSequence.test.js
  web-client/src/presenter/state.js
  web-client/src/styles/custom.scss
  web-client/src/styles/modals.scss
  web-client/src/ustc-ui/Scan/Scan.jsx
  web-client/src/ustc-ui/Scan/SelectScannerSourceModal.jsx
  web-client/src/views/StartCaseInternal.jsx
  web-client/src/views/limitFileSize.js
Labels: don't merge

#2018 1192 Eligible Cases Endpoint / Sort Tags
  efcms-service/serverless.yml
  efcms-service/src/applicationContext.js
  efcms-service/src/handlers.js
  efcms-service/src/trialSessions/getEligibleCasesForTrialSessionLambda.js
  shared/src/business/entities/Case.js
  shared/src/business/entities/Case.test.js
  shared/src/business/entities/TrialSession.js
  shared/src/business/entities/TrialSession.test.js
  shared/src/business/useCases/checkForReadyForTrialCasesInteractor.js
  shared/src/business/useCases/checkForReadyForTrialCasesInteractor.test.js
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.js
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.test.js
  shared/src/business/utilities/DateHandler.test.js
  shared/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.js
  shared/src/persistence/dynamo/trialSessions/getEligibleCasesForTrialSession.js
  shared/src/persistence/dynamo/trialSessions/getEligibleCasesForTrialSession.test.js
  shared/src/proxies/trialSessions/getEligibleCasesForTrialSessionProxy.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/TrialSession/getEligibleCasesForTrialSessionAction.js
  web-client/src/presenter/actions/TrialSession/getEligibleCasesForTrialSessionAction.test.js
Labels: IN PROGRESS, don't merge

#2132 1889 Allow multiple respondents
  efcms-service/storage/fixtures/seed/103-19.json
  shared/src/business/entities/Case.js
  shared/src/business/entities/Case.test.js
  web-client/pa11y/pa11y-respondent.js
  web-client/src/presenter/actions/getCaseAssociationAction.js
  web-client/src/presenter/actions/getCaseAssociationAction.test.js
  web-client/src/presenter/computeds/addDocketEntryHelper.js
  web-client/src/presenter/computeds/addDocketEntryHelper.test.js
  web-client/src/presenter/computeds/caseDetailHelper.js
  web-client/src/presenter/computeds/caseDetailHelper.test.js
  web-client/src/presenter/computeds/computeds.test.js
  web-client/src/presenter/computeds/formattedCaseDetail.js
  web-client/src/views/CaseDetail/PartyInformation.jsx
Labels: IN PROGRESS

#2140 OpEx - there isnt a need to have 2 record entries
  efcms-service/terraform/template/acm.tf
Labels: don't merge
