Repository flexion/ef-cms, pull requests merged in 2019-05, with the labels that each got.

#1505 1472 Update media queries
  web-client/src/styles/variables.scss
Labels: question

#1872 Node 10.16 upgrade
  efcms-service/package-lock.json
  efcms-service/package.json
  efcms-service/serverless.yml
  shared/package-lock.json
  web-client/package-lock.json
Labels: don't merge

#1911 1071 Practitioner: File Documents before associated w/ case
  efcms-service/serverless.yml
  efcms-service/src/applicationContext.js
  efcms-service/src/cases/practitionerPendingCaseAssociationLambda.js
  efcms-service/src/cases/verifyPendingCaseForUserLambda.js
  efcms-service/src/handlers.js
  shared/src/business/entities/CaseAssociationRequestFactory.js
  shared/src/business/entities/CaseAssociationRequestFactory.test.js
  shared/src/business/useCases/caseAssociationRequest/generateCaseAssociationDocumentTitleInteractor.test.js
  shared/src/business/useCases/caseAssociationRequest/submitPendingCaseAssociationRequestInteractor.js
  shared/src/business/useCases/caseAssociationRequest/submitPendingCaseAssociationRequestInteractor.test.js
  shared/src/business/useCases/caseAssociationRequest/verifyPendingCaseForUserInteractor.js
  shared/src/persistence/dynamo/cases/associateUserWithCasePending.js
  shared/src/persistence/dynamo/cases/associateUserWithCasePending.test.js
  shared/src/persistence/dynamo/cases/verifyPendingCaseForUser.js
  shared/src/persistence/dynamo/cases/verifyPendingCaseForUser.test.js
  shared/src/proxies/documents/submitPendingCaseAssociationRequestProxy.js
  shared/src/proxies/verifyPendingCaseForUserProxy.js
  web-client/e2e/journey/practitionerRequestsPendingAccessToCase.js
  web-client/e2e/journey/practitionerViewsCaseDetailOfPendingCase.js
  web-client/e2e/practitionerCaseJourney.test.js
  web-client/pa11y-ci.config.json
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/CaseAssociationRequest/generateCaseAssociationTitleAction.js
  web-client/src/presenter/actions/CaseAssociationRequest/getCaseAssociationAction.js
  web-client/src/presenter/actions/CaseAssociationRequest/getCaseAssociationAction.test.js
  web-client/src/presenter/actions/CaseAssociationRequest/setCaseAssociationAction.js
  web-client/src/presenter/actions/FileDocument/submitCaseAssociationRequestAction.js
  web-client/src/presenter/actions/FileDocument/submitCaseAssociationRequestAction.test.js
  web-client/src/presenter/actions/clearCaseAssociationWizardDataAction.js
  web-client/src/presenter/actions/clearCaseAssociationWizardDataAction.test.js
  web-client/src/presenter/computeds/caseDetailHelper.js
  web-client/src/presenter/computeds/caseDetailHelper.test.js
  web-client/src/presenter/computeds/requestAccessHelper.js
  web-client/src/presenter/sequences/gotoCaseDetailSequence.js
  web-client/src/presenter/sequences/gotoRequestAccessSequence.js
  web-client/src/presenter/sequences/reviewRequestAccessInformationSequence.js
  web-client/src/styles/custom.scss
  web-client/src/views/CaseDetail.jsx
  web-client/src/views/RequestAccess/PartiesRepresentingReadOnly.jsx
  web-client/src/views/RequestAccess/RequestAccess.jsx
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.jsx
  web-client/src/views/RequestAccess/RequestAccessDocumentReadOnly.jsx
Labels: IN PROGRESS
