Repository flexion/ef-cms, pull requests merged in 2019-01, with the labels that each got.

#511 Post-install and pre-push hooks
  efcms-service/.huskyrc.json
  efcms-service/package-lock.json
  efcms-service/package.json
  shared/.huskyrc.json
  shared/package-lock.json
  shared/package.json
  web-client/.huskyrc.json
  web-client/package-lock.json
  web-client/package.json
Labels: don't merge

#555 406 Pattern library tweaks
  web-client/src/styles/buttons.scss
  web-client/src/styles/cards.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/typography.scss
  web-client/src/views/DocumentDetail.jsx
Labels: IN PROGRESS

#641 513 Presenter & View
  efcms-service/storage/fixtures/efcms.json
  shared/package-lock.json
  shared/package.json
  shared/src/business/entities/User.js
  shared/src/business/entities/User.test.js
  shared/src/business/entities/WorkQueue.js
  shared/src/business/useCases/createDocument.interactor.test.js
  shared/src/business/useCases/getUsersInSection.interactor.js
  web-client/cypress.json
  web-client/cypress/integration/mark-case-as-paid.spec.js
  web-client/package-lock.json
  web-client/package.json
  web-client/src/presenter/actions/assignSelectedWorkItemsAction.js
  web-client/src/presenter/actions/getUsersInSectionAction.js
  web-client/src/presenter/actions/getWorkItemsForSectionAction.js
  web-client/src/presenter/sequences/assignSelectedWorkItemsSequence.js
  web-client/src/presenter/sequences/gotoDashboardSequence.js
  web-client/src/tests/assignSelectedWorkItemsAction.test.js
  web-client/src/tests/caseJourney.test.js
  web-client/src/tests/journey/dockerClerkViewsCaseDetail.js
  web-client/src/tests/journey/docketClerkViewsDashboard.js
  web-client/src/tests/journey/petitionsClerkAssignsWorkItemToSelf.js
  web-client/src/tests/journey/petitionsClerkLogIn.js
  web-client/src/tests/journey/petitionsClerkViewsDashboard.js
  web-client/src/tests/journey/respondentLogIn.js
  web-client/src/tests/journey/seniorAttorneyLogIn.js
  web-client/src/tests/selectWorkItemSequence.test.js
  web-client/src/tests/setFocusedWorkItemSequence.test.js
  web-client/src/tests/setPathAction.test.js
  web-client/src/tests/setWorkItemActionSequence.test.js
  web-client/src/tests/switchWorkQueueSequence.test.js
  web-client/src/views/DashboardPetitionsClerk.jsx
Labels: IN PROGRESS

#756 allowing the petitioner login to start cases
  shared/src/authorization/authorizationClientService.js
Labels: bug
