Repository flexion/ef-cms, pull requests merged in 2019-04, with the labels that each got.

#1360 Revert "trying circle ci"
  .circleci/config.yml
  efcms-service/package-lock.json
  efcms-service/package.json
  efcms-service/serverless.yml
  efcms-service/smoke-test-functions.js
  efcms-service/src/applicationContext.js
  efcms-service/src/middleware/apiGatewayHelper.js
  efcms-service/src/middleware/apiGatewayHelper.test.js
  get-env.sh
  shared/package-lock.json
  shared/src/business/useCases/users/createUserInteractor.test.js
  shared/src/persistence/awsDynamoPersistence.test.js
  shared/src/persistence/dynamo/cases/getCaseByCaseId.test.js
  shared/src/persistence/dynamo/cases/getCaseByDocketNumber.test.js
  shared/src/persistence/dynamo/cases/getCasesByStatus.test.js
  shared/src/persistence/dynamo/cases/getCasesByUser.test.js
  shared/src/persistence/dynamo/cases/getCasesForRespondent.test.js
  shared/src/persistence/dynamo/cases/updateCase.test.js
  shared/src/persistence/dynamo/users/getInternalUsers.test.js
  web-client/package-lock.json
Labels: don't merge

#1366 Circle CI
  .circleci/config.yml
  get-env.sh
Labels: don't merge

#1422 302: a11y, keyboard, labels and focus
  efcms-service/package-lock.json
  web-client/src/presenter/computeds/selectDocumentTypeHelper.js
  web-client/src/presenter/computeds/selectDocumentTypeHelper.test.js
  web-client/src/styles/overrides.scss
  web-client/src/views/ErrorNotification.jsx
  web-client/src/views/FileDocument/DocumentType.jsx
  web-client/src/views/FileDocument/DocumentTypeReadOnly.jsx
  web-client/src/views/FileDocument/NonstandardForm.jsx
  web-client/src/views/FileDocument/SecondaryDocumentType.jsx
  web-client/src/views/FileDocument/SecondaryDocumentTypeReadOnly.jsx
Labels: IN PROGRESS

#1513 517 deep link message
  web-client/src/presenter/actions/setMessageAsReadAction.js
  web-client/src/presenter/actions/setMessageIdFromUrlAction.js
  web-client/src/presenter/actions/workQueueClickedAction.js
  web-client/src/presenter/computeds/documentHelper.js
  web-client/src/presenter/computeds/documentHelper.test.js
  web-client/src/presenter/presenter.js
  web-client/src/presenter/sequences/gotoDocumentDetailMessageSequence.js
  web-client/src/presenter/sequences/workQueueClickedSequence.js
  web-client/src/router.js
  web-client/src/styles/cards.scss
  web-client/src/views/DocumentDetail/PendingMessages.jsx
  web-client/src/views/IndividualWorkQueueInbox.jsx
Labels: don't merge

#1535 the parcel build is not able to find the logo via path
  shared/src/business/assets/coverLogo.js
  shared/src/business/useCases/addCoverToPDFDocumentInteractor.js
Labels: bug

#1548 Specify core-js version for babel
  web-client/.babelrc
  web-client/package-lock.json
  web-client/package.json
Labels: don't merge
